"""Generate rv32_test.h from a project's own config.yaml.

rv32_test.h is the C header a test program #includes to signal
PASS/FAIL. Generating it avoids every consuming project hand-writing
and maintaining a copy that can drift out of sync with its actual
memory.mailbox_addr.
"""

from pathlib import Path

from .core import FAIL, PASS

_TEMPLATE = """\
/* Generated by riscv_tools.mailbox.generate_header from this
 * project's config.yaml (memory.mailbox_addr) — do not edit by hand,
 * edit the config and regenerate instead (`riscv-tools
 * generate-header`).
 *
 * PASS/FAIL mailbox convention: a test signals its outcome by writing
 * PASS ({pass_value}) or FAIL ({fail_value}) to RV32_MAILBOX_ADDR,
 * then calling rv32_wait_restart() (implemented in this project's
 * own crt0.S) — the host reads this address over JTAG and reloads a
 * different test onto the same, already-running hardware without
 * reprogramming it (see riscv_tools.mailbox / riscv_tools.orchestrator).
 */
#ifndef RV32_TEST_H
#define RV32_TEST_H

#define RV32_MAILBOX_ADDR ((volatile unsigned int *){addr_hex})

extern void rv32_wait_restart(void) __attribute__((noreturn));

static inline void RV32_PASS(void) {{
    *RV32_MAILBOX_ADDR = {pass_value};
    rv32_wait_restart();
}}

static inline void RV32_FAIL(void) {{
    *RV32_MAILBOX_ADDR = {fail_value};
    rv32_wait_restart();
}}

#endif /* RV32_TEST_H */
"""


def generate_header(mailbox_addr: int) -> str:
    """Render rv32_test.h's content for a given mailbox address.

    Parameters
    ----------
    mailbox_addr : int
        Byte address of the mailbox word (memory.mailbox_addr in the
        project's config.yaml).

    Returns
    -------
    str
        The full C header source.
    """
    return _TEMPLATE.format(
        addr_hex=f"0x{mailbox_addr:08X}", pass_value=PASS, fail_value=FAIL
    )


def write_header(mailbox_addr: int, out_path: Path) -> None:
    """Render and write rv32_test.h to out_path.

    Parameters
    ----------
    mailbox_addr : int
        Byte address of the mailbox word, passed through to
        generate_header.
    out_path : Path
        Path to write the header to (overwritten if it already
        exists) — typically <paths.include_dir>/rv32_test.h.

    Returns
    -------
    None
    """
    Path(out_path).write_text(generate_header(mailbox_addr))
